// PLACEHOLDER — copied from cliniqnovva/lib/firebase_options.dart (2026-08-08).
// Points at the SAME temporary Firebase project the web dashboard currently
// uses (`risingacademy-801eb`), which is itself not the real Cliniqnovva
// project — see docs/known-issues.md in the repo root. This file was never
// regenerated by `flutterfire configure` for THIS app specifically, so no
// Android/iOS app is actually registered under this projectId for
// applicationId `rw.cliniqnovva.cliniqnovva_patient` — Firebase Auth/
// Firestore calls will not succeed on a real device/emulator until that's
// done. Kept deliberately identical to the web app's (rather than left
// blank) so both clients are at least pointed at the same wrong project
// consistently, ready to be fixed together in the deferred Firebase
// project-administration session:
//   flutterfire configure --project=<real-project-id>
// run from this app's root once a real project exists.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Reuses the web dashboard's registered web app (same temporary project —
  // see file header) purely so this app can boot in a browser for local
  // testing; the patient app has no web app of its own registered.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx6cmzmoDf4UxspM5lfDCIo3gAjP6Shuw',
    appId: '1:943939108409:web:82c3ee4b54b6daf16797e8',
    messagingSenderId: '943939108409',
    projectId: 'risingacademy-801eb',
    authDomain: 'risingacademy-801eb.firebaseapp.com',
    storageBucket: 'risingacademy-801eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCESs1B01TmZ1jl6Ggd4BticYmrBY-LgRw',
    appId: '1:943939108409:android:0029fa7f55ade07c6797e8',
    messagingSenderId: '943939108409',
    projectId: 'risingacademy-801eb',
    storageBucket: 'risingacademy-801eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4YAbDMw-TiwrDIOn-k9snV9grM-CYvHc',
    appId: '1:943939108409:ios:5afcfe8ecc77504b6797e8',
    messagingSenderId: '943939108409',
    projectId: 'risingacademy-801eb',
    storageBucket: 'risingacademy-801eb.firebasestorage.app',
    iosBundleId: 'rw.cliniqnovva.cliniqnovvaPatient',
  );
}
