// PLACEHOLDER — generated by hand, not by `flutterfire configure`.
//
// No real Firebase project exists for Cliniqnovva yet. Once one does
// (cliniqnovva-dev / -staging / -prod), run:
//   flutterfire configure
// from this app's root to regenerate this file with real values. Until
// then, Firebase.initializeApp() will succeed (it doesn't validate these
// against Google's servers at init time) but any actual Auth/Firestore/
// Storage/Messaging call will fail.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'PLACEHOLDER_API_KEY',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'cliniqnovva-dev',
    authDomain: 'cliniqnovva-dev.firebaseapp.com',
    storageBucket: 'cliniqnovva-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PLACEHOLDER_API_KEY',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'cliniqnovva-dev',
    storageBucket: 'cliniqnovva-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER_API_KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'cliniqnovva-dev',
    storageBucket: 'cliniqnovva-dev.appspot.com',
    iosBundleId: 'com.cliniqnovva.cliniqnovva',
  );
}
