// Generated by `flutterfire configure` (2026-07-20), pointed at a TEMPORARY
// Firebase project (`risingacademy-801eb`, borrowed from an unrelated
// "Rising Expenses Management" app) — not Cliniqnovva's own real project.
// The web/android/ios apps registered under it were created fresh for
// Cliniqnovva by this run, so its Auth/Firestore/Storage/Messaging data is
// isolated from that other app's data. When the real cliniqnovva-dev/
// -staging/-prod project(s) exist, re-run:
//   flutterfire configure --project=<real-project-id>
// from this app's root to regenerate this file for good.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx6cmzmoDf4UxspM5lfDCIo3gAjP6Shuw',
    appId: '1:943939108409:web:82c3ee4b54b6daf16797e8',
    messagingSenderId: '943939108409',
    projectId: 'risingacademy-801eb',
    authDomain: 'risingacademy-801eb.firebaseapp.com',
    storageBucket: 'risingacademy-801eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCESs1B01TmZ1jl6Ggd4BticYmrBY-LgRw',
    appId: '1:943939108409:android:0029fa7f55ade07c6797e8',
    messagingSenderId: '943939108409',
    projectId: 'risingacademy-801eb',
    storageBucket: 'risingacademy-801eb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4YAbDMw-TiwrDIOn-k9snV9grM-CYvHc',
    appId: '1:943939108409:ios:5afcfe8ecc77504b6797e8',
    messagingSenderId: '943939108409',
    projectId: 'risingacademy-801eb',
    storageBucket: 'risingacademy-801eb.firebasestorage.app',
    iosBundleId: 'com.cliniqnovva.cliniqnovva',
  );
}
